import { NextRequest, NextResponse } from 'next/server'
import { telegram } from '@/lib/bot/telegram'
import { logger } from '@/lib/logger'
import { checkUserAndLimits } from '@/lib/bot/usageGuard'
import { logInteraction } from '@/lib/bot/analytics'

export async function POST(req: NextRequest) {
  const secret = req.headers.get('X-Telegram-Bot-Api-Secret-Token')
  
  if (process.env.TELEGRAM_WEBHOOK_SECRET && secret !== process.env.TELEGRAM_WEBHOOK_SECRET) {
    logger.warn('Unauthorized webhook request blocked.')
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    const body = await req.json()
    const message = body.message

    if (!message) return NextResponse.json({ ok: true })

    const chatId = message.chat.id
    const userText = message.text || message.caption || ""
    const photo = message.photo

    try {
      const user = await checkUserAndLimits(chatId)

      if (user.messages_used_today >= user.daily_msg_limit) {
        await telegram.sendMessage(chatId, `ΓÜá∩╕Å *Daily Limit Reached*`)
        return NextResponse.json({ ok: true })
      }

      let photoBuffer: Buffer | undefined = undefined
      if (photo && photo.length > 0) {
        await telegram.sendAction(chatId, 'typing')
        const fileInfo = await telegram.getFile(photo[photo.length - 1].file_id)
        if (fileInfo?.file_path) {
          photoBuffer = (await telegram.downloadFile(fileInfo.file_path)) || undefined
        }
      } else {
        const isImg = userText.toLowerCase().includes('draw') || userText.toLowerCase().includes('generate')
        await telegram.sendAction(chatId, isImg ? 'upload_photo' : 'typing')
      }

      // 1. Log incoming user message
      logInteraction(chatId, userText, 'user', photo ? 'image' : 'text', photo ? 'vision' : 'chat').catch(e => logger.error('User log failed', e))

      const { runChain } = await import('@/lib/bot/chainRouter')
      const result = await runChain(userText, photoBuffer, { chatId })

      // 2. Send Response
      if (result.type === 'photo') {
        await telegram.sendPhoto(chatId, result.content as Buffer, `Generated by Flowr AI Γ£¿`)
        logInteraction(chatId, '[IMAGE GENERATED]', 'model', 'image', 'chat').catch(e => logger.error('Model image log failed', e))
        
        // Post-processing for Image Usage
        const { incrementUsage } = await import('@/lib/bot/usageGuard')
        incrementUsage(user.telegram_id, 'image').catch(e => logger.error('Increment image usage failed', e))
      } else {
        await telegram.sendMessage(chatId, result.content as string)
        logInteraction(chatId, result.content as string, 'model', 'text', result.usage_type || 'chat').catch(e => logger.error('Model log failed', e))
        
        // Post-processing for Message Usage
        const { incrementUsage } = await import('@/lib/bot/usageGuard')
        incrementUsage(user.telegram_id, 'message').catch(e => logger.error('Increment message usage failed', e))
      }

    } catch (err: any) {
      if (err.message === 'USER_BLOCKED') {
        await telegram.sendMessage(chatId, '≡ƒÜ½ Suspeneded.')
      } else {
        logger.error('Flow error:', err)
        await telegram.sendMessage(chatId, 'Γ¥î *Engine Error*')
      }
    }

    return NextResponse.json({ ok: true })
  } catch (error) {
    logger.error('Webhook processing error:', error)
    return NextResponse.json({ ok: true })
  }
}
